# Generated by Django 3.2.9 on 2021-11-17 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211117_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.genre'),
        ),
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.platform'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comments',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
